/*************************************************************************
*
*               Copyright 1997 Mentor Graphics Corporation
*                         All Rights Reserved.
*
* THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY INFORMATION WHICH IS
* THE PROPERTY OF MENTOR GRAPHICS CORPORATION OR ITS LICENSORS AND IS
* SUBJECT TO LICENSE TERMS.
*
**************************************************************************
**************************************************************************
*
*   FILE NAME
*
*       chapm_1.c
*
*   COMPONENT
*
*       MSCHAP - Microsoft Challenge Handshake Authentication Protocol
*
*   DESCRIPTION
*
*       This file contains the Microsoft challenge handshake
*       authentication protocol (v1) specific functions.
*
*   DATA STRUCTURES
*
*       None
*
*   FUNCTIONS
*
*       CHAPM_1_Chal_Resp
*       CHAPM_1_Chal_Resp_Verify
*
*   DEPENDENCIES
*
*       nu_ppp.h
*
*************************************************************************/
#include "drivers/nu_ppp.h"

#if (PPP_USE_CHAP_MS1 == NU_TRUE)

/*************************************************************************
*
*   FUNCTION
*
*       CHAPM_1_Chal_Resp
*
*   DESCRIPTION
*
*       This function generates the peer response field of the response
*       packet.
*
*   INPUTS
*
*       *chal                       Authenticator Challenge Value
*       *passwd                     Password
*       *response                   24-octet response generated by this
*                                   function
*
*   OUTPUTS
*
*       None
*
*************************************************************************/
VOID CHAPM_1_Chal_Resp(UINT8 *chal, INT8 *passwd, UINT8 *response)
{
   /* Declaring Variable. */
   UINT8 passwd_hash[CHAP_MS_PASSWD_HASH_SIZE];

   /* Get the password hash. */
   CHAPM_Passwd_Hash(passwd, passwd_hash);

   /* Generate the response. */
   CHAPM_Challenge_Response(chal, passwd_hash, response);

} /* CHAPM_1_Chal_Resp */

/*************************************************************************
*
*   FUNCTION
*
*       CHAPM_1_Chal_Resp_Verify
*
*   DESCRIPTION
*
*       This function verifies the response received.
*
*   INPUTS
*
*       *chal                       Authenticator Challenge Value
*       *passwd                     Password
*       *response                   Response generated by this function
*
*   OUTPUTS
*
*       NU_TRUE                     Response verified
*       NU_FALSE                    Response is not valid
*
*************************************************************************/
STATUS CHAPM_1_Chal_Resp_Verify(UINT8 *chal, INT8 *passwd, UINT8 *response)
{
    /* Declaring Variables. */
    UINT8  my_response[CHAP_MS_RESPONSE_SIZE];
    STATUS status = NU_FALSE;

    /* Initialize my_response to remove KW error. */
    memset(my_response, 0, CHAP_MS_RESPONSE_SIZE);

    /* Generate peer response on our side. */
    CHAPM_1_Chal_Resp( chal, passwd, my_response);

    /* Compare the response received with our own. */
    if (memcmp(my_response, response, CHAP_MS_RESPONSE_SIZE) == 0)
    {
        status = NU_TRUE;
    }

    /* Return status. */
    return (status);

} /* CHAPM_1_Chal_Resp_Verify */

#endif /* PPP_USE_CHAP_MS1 == NU_TRUE */
