//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by FileConvert.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_FILECONVERT_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDI_FILE                        130
#define IDD_EDITFILE                    131
#define IDD_STATUS                      132
#define IDI_COMPRESSFILE                133
#define IDR_FILE                        134
#define IDI_SECUREFILE                  135
#define IDI_COMPSECURE                  136
#define IDD_PRIVATEDIR                  137
#define IDC_FILELIST                    1000
#define IDC_ADDFILE                     1001
#define IDC_EDIT1                       1002
#define IDC_CLEAR                       1002
#define IDC_PRIVDIR                     1002
#define IDC_EDIT2                       1003
#define IDC_EMBEDDEDNAME                1003
#define IDC_SECURE                      1003
#define IDC_BUTTON1                     1004
#define IDC_CLEARALL                    1004
#define IDC_SECUREALL                   1005
#define IDC_STATUS                      1007
#define IDC_COMPRESS                    1008
#define IDC_COMPRESSFILE                1009
#define ID_HELP_CONTENTS                1010
#define IDC_PROGRESS1                   1011
#define IDC_SECURE_CHECK                1012
#define IDC_PROGRESS2                   1012
#define IDC_PRIVATEDIR                  1013
#define IDM_SAVE                        32771
#define IDM_LOAD                        32772
#define IDC_COMPRESSALL                 32777
#define ID_COMPRESS_CLEARSELECTED       32779
#define ID_COMPRESS_CLEARALL            32780
#define ID_SECURE_CLEARSELECTED         32781
#define ID_SECURE_CLEARALL              32782
#define ID_SECURE_SETDIRECTORY          32783
#define ID_HELP_HELP                    32785

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32786
#define _APS_NEXT_CONTROL_VALUE         1018
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
